"use client";

import { useUserStore } from "@/components/providers/user-store-provider";

const messages = {
  en: {
    settings: "Settings", close: "Close settings", account: "Account", accountDescription: "Your profile and personal details", preferences: "My preferences", preferencesDescription: "Shape your development around your interests and pace", personalization: "Personalization", personalizationDescription: "Appearance, theme, and display settings",
    testProfile: "Test profile", searchEmployees: (count: number) => `Search across ${count} employees.`, findEmployee: "Find test employee", employeePlaceholder: "Name or employee ID", noEmployees: "No employees found.", department: "Department", role: "Role", workFormat: "Work format", office: "Office", hybrid: "Hybrid", remote: "Remote", tenureLabel: "Tenure", tenure: (months: number) => `${months} months`, language: "Language", careerGoal: "Career goal", notSet: "Not set yet", employee: "Employee",
    preferencesFor: "Preferences for", direction: "Your direction", goal: "Career goal", exploring: "Still exploring", grow: "Grow in my current role", promotion: "Prepare for the next grade", changeRole: "Explore a different role", targetRole: "Target role and grade", chooseTarget: "Choose a target", targetHint: "Until you choose a target, progress uses your current career path.", interests: "Skills and interests", interestsPlaceholder: "What would you like to explore or improve?", pace: "Your pace", format: "Learning format", any: "No preference", selfPaced: "Self-paced learning", workshop: "Workshops", mentoring: "Mentoring", weeklyTime: "Time per week", unsure: "Not sure yet", upToHour: "Up to 1 hour", upToTwo: "Up to 2 hours", upToFour: "Up to 4 hours", sessionNote: "Preferences are kept separately for each employee during this session and reset on page reload. They do not change the original employee record.",
    colorAccent: "Color accent", colorDescription: "Choose an accent palette and mode for your workspace.", light: "Light", dark: "Dark", system: "System", highContrast: "High contrast", contrastDescription: "Increase contrast for text and borders.", toggleContrast: "Toggle high contrast", chooseLanguage: "Interface language", languageDescription: "Choose the language used in settings.", english: "English", russian: "Русский", kazakh: "Kazakh",
    navWorkspace: "Your workspace", navDevelopment: "My development", navSkills: "Skills map", navActivities: "My activities", navHr: "Team overview", theme: "Theme", colorTheme: "Color theme", mode: "Mode",
    homeEyebrow: "Your personal journey", homeTitle: "Grow at your own pace", myGoal: "My goal", nextMilestone: "Next milestone", provisionalGoal: "Provisional goal", requirementsClosed: (met: number, total: number) => `${met} of ${total} requirements met. Skill progress is a guide, not a promise of promotion.`, onTrack: "on your way to your goal", completedQuests: "quests completed", voluntaryLearning: "Voluntary learning", skillsGrown: "skills grown", sinceReview: "Since your last review", activitiesInProgress: "activities in progress", currentFocus: "Your current focus", openSkills: "Explore your skills", understandGaps: "See your strengths and the gaps that matter", continueLearning: "Continue learning", chooseActivity: "Choose an activity", focusSkills: "Skills in focus", criticalGaps: "critical gaps", allSkillsReady: "All goal skills meet the requirements. A great starting point for a new path.", viewTrajectory: "View full trajectory", smallWins: "Small wins", demoData: "Demo · snapshot as of", changesReset: "Changes reset when you reload the page.",
  },
  ru: {
    settings: "Настройки", close: "Закрыть настройки", account: "Аккаунт", accountDescription: "Ваш профиль и личные данные", preferences: "Мои предпочтения", preferencesDescription: "Настройте развитие с учетом интересов и темпа", personalization: "Персонализация", personalizationDescription: "Внешний вид, тема и параметры отображения",
    testProfile: "Тестовый профиль", searchEmployees: (count: number) => `Поиск среди сотрудников: ${count}.`, findEmployee: "Найти тестового сотрудника", employeePlaceholder: "Имя или ID сотрудника", noEmployees: "Сотрудники не найдены.", department: "Отдел", role: "Роль", workFormat: "Формат работы", office: "Офис", hybrid: "Гибридный", remote: "Удалённо", tenureLabel: "Стаж", tenure: (months: number) => `${months} мес.`, language: "Язык", careerGoal: "Карьерная цель", notSet: "Не указана", employee: "Сотрудник",
    preferencesFor: "Предпочтения сотрудника", direction: "Ваше направление", goal: "Карьерная цель", exploring: "Пока изучаю варианты", grow: "Развиваться в текущей роли", promotion: "Подготовиться к следующему грейду", changeRole: "Рассмотреть другую роль", targetRole: "Целевая роль и грейд", chooseTarget: "Выберите цель", targetHint: "Пока цель не выбрана, прогресс рассчитывается по текущему карьерному пути.", interests: "Навыки и интересы", interestsPlaceholder: "Что вы хотели бы изучить или улучшить?", pace: "Ваш темп", format: "Формат обучения", any: "Без предпочтений", selfPaced: "Самостоятельное обучение", workshop: "Практикумы", mentoring: "Наставничество", weeklyTime: "Время в неделю", unsure: "Пока не знаю", upToHour: "До 1 часа", upToTwo: "До 2 часов", upToFour: "До 4 часов", sessionNote: "Предпочтения хранятся отдельно для каждого сотрудника в течение сессии и сбрасываются при перезагрузке. Они не изменяют исходную запись сотрудника.",
    colorAccent: "Акцентный цвет", colorDescription: "Выберите цветовую палитру и режим оформления.", light: "Светлая", dark: "Тёмная", system: "Системная", highContrast: "Высокая контрастность", contrastDescription: "Увеличить контраст текста и границ.", toggleContrast: "Переключить высокую контрастность", chooseLanguage: "Язык интерфейса", languageDescription: "Выберите язык настроек.", english: "English", russian: "Русский", kazakh: "Казахский",
    navWorkspace: "Ваше пространство", navDevelopment: "Моё развитие", navSkills: "Карта навыков", navActivities: "Мои активности", navHr: "Обзор команды", theme: "Тема", colorTheme: "Цветовая тема", mode: "Режим",
    homeEyebrow: "Ваш личный маршрут", homeTitle: "Развивайтесь в своём темпе", myGoal: "Моя цель", nextMilestone: "Следующий ориентир", provisionalGoal: "Предварительная цель", requirementsClosed: (met: number, total: number) => `${met} из ${total} требований закрыто. Прогресс по навыкам — ориентир, а не обещание повышения.`, onTrack: "на пути к цели", completedQuests: "квестов завершено", voluntaryLearning: "Добровольное обучение", skillsGrown: "навыков выросло", sinceReview: "После последней оценки", activitiesInProgress: "активностей в работе", currentFocus: "Ваш текущий фокус", openSkills: "Разобраться в навыках", understandGaps: "Что уже получается и какие разрывы важнее", continueLearning: "Продолжить обучение", chooseActivity: "Выбрать активность", focusSkills: "Навыки в фокусе", criticalGaps: "ключевых разрывов", allSkillsReady: "Все навыки цели соответствуют требованиям. Отличная точка для нового маршрута.", viewTrajectory: "Посмотреть всю траекторию", smallWins: "Маленькие победы", demoData: "Демо · срез на", changesReset: "Изменения сбрасываются после перезагрузки страницы.",
  },
} as const;

export function useSettingsI18n() {
  const language = useUserStore((state) => state.language);
  return { language, t: messages[language] };
}

export type SettingsMessages = (typeof messages)["en"];
